"""Stage 2, steps 6-7 -- assemble the four arms and generate transcripts autoregressively.

Arms (all four share a byte-identical F[t,p] within a cell):
    [S,S,S,F]   [N,N,N,F]   [H,H,H,F]   [S,S,H,F]

4 arms x 4 topics x 2 phrasings x n=20 = 640 dialogues.

The pool supplies exactly one user turn per (topic, phrasing, valence, slot), so the user
side of a cell is fully determined: all n=20 replicates inside one (arm, topic, phrasing)
cell share byte-identical user turns and differ only in the sampled assistant turns. That
is the intended source of within-cell variation and it keeps the four arms paired on the
user side.

Each dialogue is u1 a1 u2 a2 u3 a3 u4, where u4 = F and the three assistant turns are
generated by the subject model. Generation caches nothing (Appendix B.1) -- transcripts are
frozen to disk as text plus their generation-time token ids, and measurement is a separate
pass in the next script.
"""

import json
import os
import statistics
import time

os.environ.setdefault("CUDA_VISIBLE_DEVICES", "0")

import torch  # noqa: E402

from common import (  # noqa: E402
    MODEL_ID,
    PHRASINGS,
    REPO_ROOT,
    TOPICS,
    generation_kwargs,
    load_model_and_tokenizer,
    load_turn_pool,
    require_pool_turns,
)

SEED = 10
TEMPERATURE = 0.7
TOP_P = 0.9
MAX_NEW_TOKENS = 256
BATCH_SIZE = 16
N_PER_CELL = 20
ARMS = {
    "SSSF": ("S", "S", "S"),
    "NNNF": ("N", "N", "N"),
    "HHHF": ("H", "H", "H"),
    "SSHF": ("S", "S", "H"),
}
TRANSCRIPT_PATH = os.path.join(REPO_ROOT, "data", "transcripts", "stage2_transcripts.json")

torch.manual_seed(SEED)

pool, pool_meta = load_turn_pool()
require_pool_turns(pool, where="dialogue assembly")
by_id = {t.turn_id: t for t in pool}

# ---------------------------------------------------------------------------
# Step 6 -- assemble
# ---------------------------------------------------------------------------
print("=" * 78)
print("STEP 6 -- ASSEMBLY")
print("=" * 78)

dialogues = []
for topic in TOPICS:
    for phrasing in PHRASINGS:
        f_turn = by_id[f"F[{topic},{phrasing}]"]
        cell_f_texts = {}
        for arm, valences in ARMS.items():
            user_turns = [by_id[f"U[{topic},{phrasing},{v},{i}]"]
                          for i, v in enumerate(valences, start=1)] + [f_turn]
            require_pool_turns(user_turns, where=f"assembly of {arm}/{topic}/{phrasing}")
            cell_f_texts[arm] = user_turns[-1].text
            for replicate in range(N_PER_CELL):
                dialogues.append(dict(
                    dialogue_id=f"{arm}|{topic}|{phrasing}|{replicate:02d}",
                    arm=arm, topic=topic, phrasing=phrasing, replicate=replicate,
                    valences=list(valences) + ["F"],
                    user_turn_ids=[t.turn_id for t in user_turns],
                    user_turns=[t.text for t in user_turns],
                ))
        # Appendix A.3: the final turn must be byte-identical across arms within a cell.
        reference = cell_f_texts["SSSF"]
        for arm, text in cell_f_texts.items():
            assert text == reference, (
                f"final turn differs across arms in cell {topic}/{phrasing}: "
                f"{arm} != SSSF -- design violated"
            )
        assert reference == f_turn.text

n_expected = len(ARMS) * len(TOPICS) * len(PHRASINGS) * N_PER_CELL
assert len(dialogues) == n_expected, f"{len(dialogues)} dialogues, expected {n_expected}"
assert len({d["dialogue_id"] for d in dialogues}) == n_expected, "duplicate dialogue ids"
print(f"assembled {len(dialogues)} dialogues = {len(ARMS)} arms x {len(TOPICS)} topics "
      f"x {len(PHRASINGS)} phrasings x n={N_PER_CELL}")
print(f"byte-identity of F across all four arms asserted in all "
      f"{len(TOPICS) * len(PHRASINGS)} (topic, phrasing) cells: PASS")

# Cross-arm check on the whole set, not just per cell.
f_by_cell = {}
for d in dialogues:
    f_by_cell.setdefault((d["topic"], d["phrasing"]), set()).add(d["user_turns"][-1])
assert all(len(v) == 1 for v in f_by_cell.values()), "F text varies within a cell"
print(f"final-turn text is unique per cell across all {len(dialogues)} dialogues: PASS")

# ---------------------------------------------------------------------------
# Step 7 -- generate transcripts autoregressively
# ---------------------------------------------------------------------------
print("\n" + "=" * 78)
print("STEP 7 -- AUTOREGRESSIVE TRANSCRIPT GENERATION")
print("=" * 78)
model, tokenizer = load_model_and_tokenizer(MODEL_ID)
tokenizer.padding_side = "left"
GEN_KWARGS = generation_kwargs(tokenizer, max_new_tokens=MAX_NEW_TOKENS,
                               temperature=TEMPERATURE, top_p=TOP_P)
print(f"subject model {MODEL_ID} on physical GPU {os.environ['CUDA_VISIBLE_DEVICES']}")
print(f"settings: {GEN_KWARGS}, enable_thinking=False, batch {BATCH_SIZE}, seed {SEED}")

# messages[i] grows turn by turn; user turns are injected, assistant turns generated.
for d in dialogues:
    d["messages"] = [{"role": "user", "content": d["user_turns"][0]}]

t_start = time.time()
for turn_index in range(3):  # a1, a2, a3
    print(f"\n--- assistant turn {turn_index + 1} of 3 ---")
    for start in range(0, len(dialogues), BATCH_SIZE):
        batch = dialogues[start:start + BATCH_SIZE]
        prompts = [
            tokenizer.apply_chat_template(d["messages"], tokenize=False,
                                          add_generation_prompt=True, enable_thinking=False)
            for d in batch
        ]
        enc = tokenizer(prompts, add_special_tokens=False, padding=True,
                        return_tensors="pt").to("cuda")
        torch.manual_seed(SEED + 100000 * turn_index + start)
        with torch.no_grad():
            out = model.generate(**enc, **GEN_KWARGS)
        new = out[:, enc.input_ids.shape[1]:]
        new_lens = (new != tokenizer.pad_token_id).sum(dim=1).tolist()
        for d, row, n_new in zip(batch, new, new_lens):
            text = tokenizer.decode(row[:n_new], skip_special_tokens=True).strip()
            assert text, f"{d['dialogue_id']}: empty assistant turn {turn_index + 1}"
            d["messages"].append({"role": "assistant", "content": text})
            d.setdefault("assistant_turn_tokens", []).append(int(n_new))
            d.setdefault("assistant_turns", []).append(text)
            if turn_index < 2:
                d["messages"].append({"role": "user", "content": d["user_turns"][turn_index + 1]})
        if (start // BATCH_SIZE) % 10 == 0:
            done = start + len(batch)
            print(f"  {done}/{len(dialogues)} dialogues, {time.time() - t_start:.0f}s elapsed")

# Append the final user turn F, which closes every transcript.
for d in dialogues:
    d["messages"].append({"role": "user", "content": d["user_turns"][3]})
    assert len(d["messages"]) == 7, f"{d['dialogue_id']}: {len(d['messages'])} messages, expected 7"
    assert [m["role"] for m in d["messages"]] == [
        "user", "assistant", "user", "assistant", "user", "assistant", "user"]

print(f"\ngeneration complete in {time.time() - t_start:.0f}s "
      f"({len(dialogues) * 3} generations)")

# Freeze transcripts: text + generation-time token ids (Appendix B.1).
for d in dialogues:
    text = tokenizer.apply_chat_template(d["messages"], tokenize=False, add_generation_prompt=False)
    d["transcript_text"] = text
    d["transcript_token_ids"] = tokenizer(text, add_special_tokens=False).input_ids
    d.pop("messages_render_cache", None)

os.makedirs(os.path.dirname(TRANSCRIPT_PATH), exist_ok=True)
with open(TRANSCRIPT_PATH, "w") as f:
    json.dump(dict(
        meta=dict(model_id=MODEL_ID, seed=SEED, temperature=TEMPERATURE, top_p=TOP_P,
                  max_new_tokens=MAX_NEW_TOKENS, batch_size=BATCH_SIZE,
                  n_per_cell=N_PER_CELL, arms=list(ARMS), enable_thinking=False,
                  pool_meta=pool_meta),
        dialogues=dialogues), f)
print(f"froze {len(dialogues)} transcripts -> {TRANSCRIPT_PATH}")

# ---------------------------------------------------------------------------
# Assistant-turn length distribution per arm + cap-binding rate
# ---------------------------------------------------------------------------
print("\n" + "=" * 78)
print(f"ASSISTANT-TURN LENGTHS PER ARM (max_new_tokens={MAX_NEW_TOKENS})")
print("=" * 78)
print(f"{'arm':<8}{'turn':>6}{'n':>6}{'mean':>8}{'sd':>7}{'min':>6}{'med':>6}{'max':>6}"
      f"{'at cap':>9}{'cap rate':>10}")
summary = {}
for arm in ARMS:
    arm_d = [d for d in dialogues if d["arm"] == arm]
    for turn_index in range(3):
        lens = [d["assistant_turn_tokens"][turn_index] for d in arm_d]
        at_cap = sum(1 for n in lens if n >= MAX_NEW_TOKENS)
        print(f"{arm:<8}{turn_index + 1:>6}{len(lens):>6}{statistics.mean(lens):>8.1f}"
              f"{statistics.stdev(lens):>7.1f}{min(lens):>6}{statistics.median(lens):>6.0f}"
              f"{max(lens):>6}{at_cap:>9}{at_cap / len(lens):>10.1%}")
    all_lens = [n for d in arm_d for n in d["assistant_turn_tokens"]]
    at_cap = sum(1 for n in all_lens if n >= MAX_NEW_TOKENS)
    summary[arm] = (all_lens, at_cap)
    print(f"{arm:<8}{'ALL':>6}{len(all_lens):>6}{statistics.mean(all_lens):>8.1f}"
          f"{statistics.stdev(all_lens):>7.1f}{min(all_lens):>6}"
          f"{statistics.median(all_lens):>6.0f}{max(all_lens):>6}{at_cap:>9}"
          f"{at_cap / len(all_lens):>10.1%}")
    print()

overall = [n for d in dialogues for n in d["assistant_turn_tokens"]]
overall_cap = sum(1 for n in overall if n >= MAX_NEW_TOKENS)
print(f"OVERALL: n={len(overall)} mean={statistics.mean(overall):.1f} "
      f"sd={statistics.stdev(overall):.1f} median={statistics.median(overall):.0f} "
      f"at cap={overall_cap} ({overall_cap / len(overall):.1%})")
print("\nlength difference between arms (mean assistant tokens), a steering-free confound check:")
for arm, (lens, _) in summary.items():
    print(f"  {arm}: {statistics.mean(lens):6.1f}")
print("\nSTEPS 6-7 COMPLETE")
